/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'customerPhone' : string,
  'date' : string,
  'specialRequests' : string,
  'createdAt' : bigint,
  'partySize' : bigint,
  'timeSlot' : string,
  'eventType' : string,
}
export interface Member {
  'id' : bigint,
  'referralCode' : string,
  'name' : string,
  'joinedAt' : bigint,
  'tier' : string,
  'email' : string,
  'totalVisits' : bigint,
  'totalPoints' : bigint,
  'phone' : string,
}
export interface MenuItem {
  'id' : bigint,
  'isChefRecommended' : boolean,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
  'dietaryTags' : Array<string>,
  'spiceLevel' : bigint,
  'category' : string,
  'rating' : bigint,
  'price' : bigint,
}
export interface Review {
  'id' : bigint,
  'customerName' : string,
  'createdAt' : bigint,
  'comment' : string,
  'rating' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMemberPoints' : ActorMethod<[bigint, bigint], undefined>,
  'addMenuItem' : ActorMethod<[MenuItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint, string], undefined>,
  'createBooking' : ActorMethod<[Booking], bigint>,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'deleteReview' : ActorMethod<[bigint], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getBookingsForDate' : ActorMethod<[string], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMemberByPhone' : ActorMethod<[string], [] | [Member]>,
  'getMenuItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSlotAvailable' : ActorMethod<[string, string], boolean>,
  'registerMember' : ActorMethod<[Member], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitReview' : ActorMethod<[Review], undefined>,
  'toggleMenuItemAvailability' : ActorMethod<[bigint], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, string], undefined>,
  'updateMenuItem' : ActorMethod<[bigint, MenuItem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];