/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'isChefRecommended' : IDL.Bool,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'dietaryTags' : IDL.Vec(IDL.Text),
  'spiceLevel' : IDL.Nat,
  'category' : IDL.Text,
  'rating' : IDL.Nat,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'customerPhone' : IDL.Text,
  'date' : IDL.Text,
  'specialRequests' : IDL.Text,
  'createdAt' : IDL.Int,
  'partySize' : IDL.Nat,
  'timeSlot' : IDL.Text,
  'eventType' : IDL.Text,
});
export const Member = IDL.Record({
  'id' : IDL.Nat,
  'referralCode' : IDL.Text,
  'name' : IDL.Text,
  'joinedAt' : IDL.Int,
  'tier' : IDL.Text,
  'email' : IDL.Text,
  'totalVisits' : IDL.Nat,
  'totalPoints' : IDL.Nat,
  'phone' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'createdAt' : IDL.Int,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMemberPoints' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'addMenuItem' : IDL.Func([MenuItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'createBooking' : IDL.Func([Booking], [IDL.Nat], []),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
  'deleteReview' : IDL.Func([IDL.Nat], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getBookingsForDate' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMemberByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSlotAvailable' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'registerMember' : IDL.Func([Member], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitReview' : IDL.Func([Review], [], []),
  'toggleMenuItemAvailability' : IDL.Func([IDL.Nat], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateMenuItem' : IDL.Func([IDL.Nat, MenuItem], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'isChefRecommended' : IDL.Bool,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'dietaryTags' : IDL.Vec(IDL.Text),
    'spiceLevel' : IDL.Nat,
    'category' : IDL.Text,
    'rating' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'customerPhone' : IDL.Text,
    'date' : IDL.Text,
    'specialRequests' : IDL.Text,
    'createdAt' : IDL.Int,
    'partySize' : IDL.Nat,
    'timeSlot' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const Member = IDL.Record({
    'id' : IDL.Nat,
    'referralCode' : IDL.Text,
    'name' : IDL.Text,
    'joinedAt' : IDL.Int,
    'tier' : IDL.Text,
    'email' : IDL.Text,
    'totalVisits' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'createdAt' : IDL.Int,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMemberPoints' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'addMenuItem' : IDL.Func([MenuItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createBooking' : IDL.Func([Booking], [IDL.Nat], []),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
    'deleteReview' : IDL.Func([IDL.Nat], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getBookingsForDate' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMemberByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSlotAvailable' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'registerMember' : IDL.Func([Member], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitReview' : IDL.Func([Review], [], []),
    'toggleMenuItemAvailability' : IDL.Func([IDL.Nat], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateMenuItem' : IDL.Func([IDL.Nat, MenuItem], [], []),
  });
};

export const init = ({ IDL }) => { return []; };